backend/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('', include('home.urls')),
    path('user/', include('user.urls'))
]

backend/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing_page'),
    path('<str:fundation_type>', views.LandingPageView.as_view(), name='landing_page_args'),
    path('donation/', views.AddDonationView.as_view(), name='add_donation'),
    path('donation/confirmation/', views.DonationConfirmationView.as_view(), name='donation_confirmation'),
    path('send/contact-form', views.ContactFormView.as_view(), name='contact_form')
]

backend/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login', views.LoginUserView.as_view(), name='login'),
    path('register', views.RegiserUserView.as_view(), name='register'),
    path('logout', views.UserLogoutView.as_view(), name='logout'),
    path('detail/<str:info>', views.UserDetailView.as_view(), name='detail'),
    path('donation/<int:pk>', views.UserDonationUpdateStatusView.as_view(), name='taken'),
    path('password', views.UserChangePasswordView.as_view(), name='password'),
    path('activate/<int:pk>/<str:token>', views.ActivateUserView.as_view(), name='activate'),
    path('reset_password', views.ResetPasswordGenerateTokenView.as_view(), name='reset_password'),
    path('reset/<str:token>', views.ResetPasswordValidateTokenChangePassword.as_view(),
         name='reset_password_token'),
]

backend/home/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f'Category: {self.name}'


class Institution(models.Model):
    class Types(models.TextChoices):
        FUNDATION = 'FUN', 'Fundacja'
        NGO = 'NGO', 'Organizacja Pozarządowa'
        LOCAL_COLLECTION = 'LOC', 'Zbiórka Lokalna'

    name = models.CharField(max_length=150)
    decription = models.TextField(max_length=1000)
    type = models.CharField(choices=Types.choices, default=Types.FUNDATION, max_length=25)
    categories = models.ManyToManyField('Category', related_name='instotution_categories')

    def __str__(self):
        return f'Institution: {self.name}'


class Donation(models.Model):
    quantity = models.PositiveIntegerField()
    categories = models.ManyToManyField('Category', related_name='dontaion_categories')
    institution = models.ForeignKey('Institution', on_delete=models.CASCADE, related_name='donations')
    address = models.CharField(max_length=300)
    phone_number = models.CharField(max_length=15)
    city = models.CharField(max_length=150)
    zip_code = models.CharField(max_length=50)
    pick_up_date = models.DateTimeField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.TextField(max_length=500)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, null=True, blank=True, on_delete=models.CASCADE)
    is_taken = models.BooleanField(default=False)

    def __str__(self):
        return f'Donation: Address - {self.address}, City - {self.city}'


class UserMessageToAdmin(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField(max_length=1000)

    def __str__(self):
        return f'UserMessageToAdmin: Name - {self.name}, Email - {self.email}'

backend/home/views.py
import json

from django.http import HttpResponse
from django.db import DatabaseError
from django.db.models.aggregates import Sum
from django.views.generic import TemplateView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect

from . import models


class LandingPageView(ListView):
    template_name = 'home/landingpage.html'
    model = models.Institution
    context_object_name = 'institutions'
    paginate_by = 5
    ordering = ['name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['counts'] = {
            'institutions_count': self.model.objects.count(),
            'bags_count': models.Donation.objects.aggregate(Sum('quantity'))
        }
        return context

    def get_queryset(self):
        if not self.kwargs.get('fundation_type'):
            return models.Institution.objects.filter(type='FUN')
        return models.Institution.objects.filter(type=self.kwargs['fundation_type'].strip())


class AddDonationView(LoginRequiredMixin, TemplateView):
    template_name = 'home/form.html'
    login_url = reverse_lazy('user:login')
    redirect_field_name = reverse_lazy('user:register')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = models.Category.objects.all()
        context['institutions'] = models.Institution.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        data_from_user = json.loads(self.request.body)
        try:
            donation = models.Donation.objects.create(
                quantity=data_from_user['bagCount'],
                institution_id=data_from_user['organizationId'],
                address=data_from_user['userStreet'],
                phone_number=data_from_user['userPhone'],
                city=data_from_user['userCity'],
                zip_code=data_from_user['userPostCode'],
                pick_up_date=data_from_user['userDate'],
                pick_up_time=data_from_user['userTime'],
                pick_up_comment=data_from_user['userPickUpComment'],
                user=self.request.user,
                # TODO: Set default value in model
            )
            donation.save()
            return HttpResponse(status=200)

        except DatabaseError:
            return HttpResponse(status=400)


class DonationConfirmationView(LoginRequiredMixin, TemplateView):
    template_name = 'home/form-confirmation.html'


class ContactFormView(View):
    def post(self, *args, **kwargs):
        data = json.loads(self.request.body)

        name, email, message = data['userName']['value'], data['userEmail']['value'], data['userMessage']['value']

        if not name or not email or not message:
            return HttpResponse(status=400)

        try:
            user_message = models.UserMessageToAdmin.objects.create(
                name=name,
                email=email,
                message=message
            )
            user_message.save()
            return HttpResponse(status=200, content='Wiadomość została wysłana')
        except DatabaseError:
            return HttpResponse(status=400, content='Wystąpił błąd podczas wysyłania wiadomości')

backend/home/templates/home/form-confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {% endblock %}

{% block content %}

    <header>
        <nav class="container container--70">
            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>

        <body>
            <div class="slogan container container--90">
                <h2>
                    Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
                    informacje o odbiorze.
                </h2>
            </div>
        </body>
    </header>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/home/templates/home/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {% endblock %}

{% block content %}
    <body>
    <header class="header--form-page">
        <nav class="container container--70">
            <ul class="nav--actions">
                <li class="logged-user">
                    {% if user.is_authenticated %}
                        Witaj {{ user.username }}
                        <ul class="dropdown">
                            <li><a href="{% url 'user:detail' 'realized_donations' %}">Profil</a></li>
                            <li><a href="{% url 'user:password'  %}">Ustawienia</a></li>
                            {% if user.is_superuser %}
                                <li><a href="/admin/">Panel Administracyjny</a></li>
                            {% endif %}
                                <li><a href="{% url 'user:logout' %}">Wyloguj</a></li>
                        </ul>
                    {% endif %}
                </li>
            </ul>

            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>

            </ul>
        </nav>

        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    Oddaj rzeczy, których już nie chcesz<br/>
                    <span class="uppercase">potrzebującym</span>
                </h1>

                <div class="slogan--steps">
                    <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
                    <ul class="slogan--steps-boxes">
                        <li>
                            <div><em>1</em><span>Wybierz rzeczy</span></div>
                        </li>
                        <li>
                            <div><em>2</em><span>Spakuj je w worki</span></div>
                        </li>
                        <li>
                            <div><em>3</em><span>Wybierz fundację</span></div>
                        </li>
                        <li>
                            <div><em>4</em><span>Zamów kuriera</span></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <section class="form--steps">
        <div class="form--steps-instructions">
            <div class="form--steps-container">
                <h3>Ważne!</h3>
                <p data-step="1" class="active">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="2">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="3">
                    Wybierz jedną, do
                    której trafi Twoja przesyłka.
                </p>
                <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
            </div>
        </div>

        <div class="form--steps-container">
            <div class="form--steps-counter">Krok <span>1</span>/5</div>

            <form action="form-confirmation.html" method="post">
                <!-- STEP 1: class .active is switching steps -->
                <div data-step="1" class="active">
                    <h3>Zaznacz co chcesz oddać:</h3>

                    {% for category in categories %}


                        <div class="form-group form-group--checkbox">
                            <label>
                                <input
                                        type="checkbox"
                                        name="categories"
                                        value="{{ category.name }}"
                                />
                                <span class="checkbox"></span>
                                <span class="description"
                                >{{ category.name }}</span
                                >
                            </label>
                        </div>


                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn next-step cat-event">Dalej</button>
                    </div>
                </div>

                <!-- STEP 2 -->
                <div data-step="2">
                    <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

                    <div class="form-group form-group--inline">
                        <label>
                            Liczba 60l worków:
                            <input type="number" name="bags" step="1" min="1"/>
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step institution-show-reset stage-2">Wstecz</button>
                        <button type="button" class="btn next-step stage-2">Dalej</button>
                    </div>
                </div>


                <!-- STEP 4 -->
                <div data-step="3">
                    <h3>Wybierz organizacje, której chcesz pomóc:</h3>

                    {% for institution in institutions %}

                        <div class="form-group form-group--checkbox to-filter institution">
                            <label>
                                <input type="radio" name="organization" value="old"
                                       data-institution-id="{{ institution.id }}"
                                       data-institution-name="{{ institution.name }}"/>
                                <span class="checkbox radio"></span>
                                <span class="description"
                                      data-category="
                                      {% for category in institution.categories.all %}
                                      {{ category.name }},
                                      {% endfor %}
                                        ">
                                    <div class="title">Fundacja “{{ institution.name }}”</div>
                                    <div class="subtitle">

                                    Cel i misja: {{ institution.decription }} </div>
                                </span>
                            </label>
                        </div>
                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step stage-4">Dalej</button>
                    </div>
                </div>

                <!-- STEP 5 -->
                <div data-step="4">
                    <h3>Podaj adres oraz termin odbioru rzeczy przez kuriera:</h3>

                    <div class="form-section form-section--columns">
                        <div class="form-section--column">
                            <h4>Adres odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Ulica <input type="text" name="address"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Miasto <input type="text" name="city"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Kod pocztowy <input type="text" name="postcode"/>
                                </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Numer telefonu <input type="phone" name="phone"/>
                                </label>
                            </div>
                        </div>

                        <div class="form-section--column">
                            <h4>Termin odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Data <input type="date" name="data"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Godzina <input type="time" name="time"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Uwagi dla kuriera
                                    <textarea name="more_info" rows="5"></textarea>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step stage-5">Dalej</button>
                    </div>
                </div>

                <!-- STEP 6 -->
                <div data-step="5">
                    <h3>Podsumowanie Twojej darowizny</h3>

                    <div class="summary">
                        <div class="form-section">
                            <h4>Oddajesz:</h4>
                            <ul>
                                <li>
                                    <span class="icon icon-bag"></span>
                                    <span class="summary--text" id="bags"
                                    >4 worki ubrań w dobrym stanie dla dzieci</span
                                    >
                                </li>

                                <li>
                                    <span class="icon icon-hand"></span>
                                    <span class="summary--text" id="organization"
                                    >Dla fundacji "Mam marzenie" w Warszawie</span
                                    >
                                </li>
                            </ul>
                        </div>

                        <div class="form-section form-section--columns">
                            <div class="form-section--column">
                                <h4>Adres odbioru:</h4>
                                <ul>
                                    <li id="address">Prosta 51</li>
                                    <li id="city">Warszawa</li>
                                    <li id="post-code">99-098</li>
                                    <li id="phone">123 456 789</li>
                                </ul>
                            </div>

                            <div class="form-section--column">
                                <h4>Termin odbioru:</h4>
                                <ul>
                                    <li id="date">13/12/2018</li>
                                    <li id="hour">15:40</li>
                                    <li id="more_info">Brak uwag</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="submit" class="btn stage-6">Potwierdzam</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    </body>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/categories-donation-form-min.js' %}" defer async></script>
    <script src="{% static 'scripts/donation-form-min.js' %}" defer async></script>
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/home/templates/home/landingpage.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {% endblock %}

{% block content %}

    {% if  user.is_authenticated %}
        <body>
        <header class="header--form-page">
        <nav class="container container--70">
            <ul class="nav--actions">
                <li class="logged-user">
                    Witaj {{ user.username }}
                    <ul class="dropdown">
                        <li><a href="{% url 'user:detail' 'realized_donations' %}">Profil</a></li>
                        <li><a href="{% url 'user:password' %}">Ustawienia</a></li>
                        {% if user.is_superuser %}
                            <li><a href="/admin/">Panel Administracyjny</a></li>
                        {% endif %}
                        <li><a href="{% url 'user:logout' %}">Wyloguj</a></li>
                    </ul>
                </li>
            </ul>

            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>

            </ul>
        </nav>
    {% else %}
        <header class="header--main-page">
        <nav class="container container--70">
            {% if user.is_authenticated %}
                <ul class="nav--actions">
                    <li><a href="{% url 'user:detail' %}" class="btn btn--small btn--without-border">Profil</a></li>
                </ul>
            {% else %}
                <ul class="nav--actions">
                    <li><a href="{% url 'user:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
                    <li><a href="{% url 'user:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
                </ul>
            {% endif %}


            <ul>
                <li><a href="" class="btn btn--without-border active">Start</a></li>
                <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>


    {% endif %}


<div class="slogan container container--90">
    <div class="slogan--item">
        <h1>
            Zacznij pomagać!<br/>
            Oddaj niechciane rzeczy w zaufane ręce
        </h1>
    </div>
</div>
</header>

    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em> {{ counts.bags_count.quantity__sum|default:'0' }}</em>
                <h3>Oddanych worków</h3>
                <p>Możesz przyczynić się do wzrostu tej liczby, wystarczy, że utworzysz konto w serwisie i zdecydujesz
                    się przekazać darowiznę.</p>
            </div>

            <div class="stats--item">
                <em>{{ counts.institutions_count|default:"0" }}</em>
                <h3>Wspartych organizacji</h3>
                <p>Możesz przyczynić się do wzrostu tej liczby, wystarczy, że utworzysz konto w serwisie i zdecydujesz
                    się przekazać darowiznę.</p>
            </div>

        </div>
    </section>

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>

        <a href="{% url 'user:register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Projekt wykonany w ramach treningu z django, odwiedź kota i sprawdź resztę projektów <a
                    href="https://github.com/MWasile"><img
                    src="{% static 'images/icons8-github-24.png' %}" alt="github-icon"></a></p>
        </div>
        <div class="about-us--image"><img src="{% static 'images/about-us.jpg' %}" alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="{% url 'home:landing_page_args' 'FUN' %}  #help" class="XD">Fundacjom</a></li>
            <li data-id="2"><a href="{% url 'home:landing_page_args' 'NGO' %} #help" class="XD">Organizacjom
                pozarządowym</a></li>
            <li data-id="3"><a href="{% url 'home:landing_page_args' 'LOC' %} #help" class="XD">Lokalnym zbiórkom</a>
            </li>
        </ul>

        <!-- SLIDE 1 -->


        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.</p>
            {% for institution in institutions %}
                <ul class="help--slides-items">
                    <li>
                        <div class="col">
                            <div class="title">Fundacja "{{ institution.name }}"</div>
                            <div class="subtitle">Cel i misja: {{ institution.decription }}.</div>
                        </div>
                        <div class="col">
                            <div class="text">ubrania, jedzenie, sprzęt AGD, meble, zabawki</div>
                        </div>
                    </li>
                </ul>
            {% endfor %}

            <ul class="help--slides-pagination">

                {% for page_number in paginator.page_range %}

                    {% if page_obj.number == page_number %}
                        <li><a href="?page={{ page_number }} #help" style="font-size:1.7em;">{{ page_number }}</a></li>
                    {% else %}
                        <li><a href="?page={{ page_number }} #help">{{ page_number }}</a></li>
                    {% endif %}

                {% endfor %}

            </ul>
        </div>
    </section>

{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}