backend/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('', include('home.urls')),
    path('user/', include('user.urls'))
]

backend/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing_page'),
    path('<str:fundation_type>', views.LandingPageView.as_view(), name='landing_page_args'),
    path('donation/', views.AddDonationView.as_view(), name='add_donation'),
    path('donation/confirmation/', views.DonationConfirmationView.as_view(), name='donation_confirmation'),
    path('send/contact-form', views.ContactFormView.as_view(), name='contact_form')
]

backend/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login', views.LoginUserView.as_view(), name='login'),
    path('register', views.RegiserUserView.as_view(), name='register'),
    path('logout', views.UserLogoutView.as_view(), name='logout'),
    path('detail/<str:info>', views.UserDetailView.as_view(), name='detail'),
    path('donation/<int:pk>', views.UserDonationUpdateStatusView.as_view(), name='taken'),
    path('password', views.UserChangePasswordView.as_view(), name='password'),
    path('activate/<int:pk>/<str:token>', views.ActivateUserView.as_view(), name='activate'),
    path('reset_password', views.ResetPasswordGenerateTokenView.as_view(), name='reset_password'),
    path('reset/<str:token>', views.ResetPasswordValidateTokenChangePassword.as_view(),
         name='reset_password_token'),
]

backend/user/models.py
from django.db import models
from django.conf import settings


class UserResetToken(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    token = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    used = models.BooleanField(default=False)

    def __str__(self):
        return self.token

backend/user/forms.py
from django import forms
from django.contrib.auth import get_user_model


class ReigsterUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password', 'last_name']

    def clean_email(self):
        email = self.cleaned_data['email']

        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')

        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        re_password = self.data['re_password']

        if password != re_password:
            raise forms.ValidationError('Passwords do not match')

        if len(password) < 6:
            raise forms.ValidationError('Password must be at least 6 characters')

        return password

    def clean_username(self):
        username = self.cleaned_data['username']

        if get_user_model().objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exists')

        return username

    def create_new_user(self):
        return get_user_model().objects.create_user(
            username=self.cleaned_data['username'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'],
            is_active=False
        )


class LoginUserForm(forms.Form):
    user_email = forms.CharField(max_length=255)
    password = forms.CharField(max_length=200)

    def clean_user_email(self):
        user_email = self.cleaned_data['user_email']

        if not get_user_model().objects.filter(email=user_email).exists():
            raise forms.ValidationError('Email doesnt exist.')

        return user_email

    def clean_password(self):
        password = self.cleaned_data['password']
        user_email = self.data.get('user_email')

        user = get_user_model().objects.filter(email=user_email).first()

        if not user:
            raise forms.ValidationError('User doesnt exist')

        if not user.check_password(password):
            raise forms.ValidationError('Incorrect password.')

        return password


class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(max_length=200)
    new_password = forms.CharField(max_length=200)
    re_new_password = forms.CharField(max_length=200)

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        re_new_password = self.data['re_new_password']

        print(vars(self))

        if new_password != re_new_password:
            raise forms.ValidationError('Passwords do not match')

        if len(new_password) < 6:
            raise forms.ValidationError('Password must be at least 6 characters')

        return new_password


class PasswordResetEmailCheckerForm(forms.Form):
    email = forms.CharField(max_length=255)

    def clean_email(self):
        email = self.cleaned_data['email']

        if not self.cleaned_data['email']:
            raise forms.ValidationError('Wpisz poprawny e-mail.')

        if not get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Podany e-email nie istnieje.')

        return email


class PaswordResetSetPasswordForm(forms.Form):
    new_password = forms.CharField(max_length=200)
    re_new_password = forms.CharField(max_length=200)

    def clean_new_password(self):
        password = self.cleaned_data['new_password']
        re_password = self.data['re_new_password']

        if password != re_password:
            raise forms.ValidationError('Hasła nie są identyczne!.')

        return password

backend/user/views.py
from django.views.generic import TemplateView, FormView, View
from django.contrib.auth import login, logout, get_user_model
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages

from . import forms
from . import tokens
from . import models
from home.models import Donation


class LoginUserView(FormView):
    template_name = 'user/login.html'
    form_class = forms.LoginUserForm
    success_url = reverse_lazy('home:landing_page')

    def form_invalid(self, form):
        if form.errors.get('user_email'):
            return redirect(reverse_lazy('user:register'))
        return super().form_invalid(form)

    def form_valid(self, form):
        user = get_user_model().objects.get(email=form.cleaned_data['user_email'])

        if not user.is_active:
            messages.add_message(self.request, messages.ERROR, 'Twoje konto nie zostało aktywowane.')
            return super().form_invalid(form)

        login(self.request, user)

        return super().form_valid(form)


class RegiserUserView(FormView):
    template_name = 'user/register.html'
    form_class = forms.ReigsterUserForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        new_user = form.create_new_user()
        self.send_activation_email(new_user)
        return super().form_valid(form)

    def send_activation_email(self, user):
        token = tokens.token_generator.make_token(user)
        domain = 'unused-items.maciejwasilewski.pl'
        user.email_user(
            'Activate your account',
            f'Please click the link to activate your account: https://{domain}/user/activate/{user.pk}/{token}')
        messages.add_message(self.request, messages.INFO, 'Na podany adres email został wysłany link aktywacyjny.')


class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse_lazy('home:landing_page'))


class UserDetailView(TemplateView):
    template_name = 'user/detail.html'

    def get_context_data(self, **kwargs):
        info = self.kwargs['info']
        context = super().get_context_data(**kwargs)
        print(info, 'XDDD')
        if info == 'donations_in_progress' or not info:
            context['donations_in_progress'] = Donation.objects.filter(user=self.request.user, is_taken=False)
        elif info == 'realized_donations':
            context['realized_donations'] = Donation.objects.filter(user=self.request.user, is_taken=True)
        elif info == 'user_detail':
            context['user_detail'] = get_user_model().objects.get(pk=self.request.user.pk)

        print(context)

        return context


class UserDonationUpdateStatusView(View):
    def get(self, request, *args, **kwargs):
        donation = Donation.objects.get(id=kwargs.get('pk'))
        donation.is_taken = True
        donation.save()
        return redirect(reverse_lazy('user:detail', kwargs={'info': 'donations_in_progress'}))


class UserChangePasswordView(FormView):
    template_name = 'user/change_password.html'
    form_class = forms.PasswordChangeForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        user = get_user_model().objects.get(id=self.request.user.id)

        if user.check_password(form.cleaned_data['old_password']):
            user.set_password(form.cleaned_data['new_password'])
            user.save()
            return super().form_valid(form)

        form.add_error('old_password', 'Wrong password')
        return super().form_invalid(form)


class ActivateUserView(View):
    def get(self, request, *args, **kwargs):
        user = get_user_model().objects.get(id=kwargs.get('pk'))

        if tokens.token_generator.check_token(user, kwargs.get('token')):
            user.is_active = True
            user.save()
            messages.success(request, 'Dzękujemy za aktywację konta!')
            return redirect(reverse_lazy('user:login'))
        return redirect(reverse_lazy('home:landing_page'))


class ResetPasswordGenerateTokenView(FormView):
    template_name = 'user/password_reset.html'
    form_class = forms.PasswordResetEmailCheckerForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        user = get_user_model().objects.get(email=form.cleaned_data['email'])
        token = tokens.password_reset_token.make_token(user)

        models.UserResetToken.objects.create(
            user=user,
            token=token
        )

        messages.success(self.request, 'Email z linkiem do zmiany hasła został wysłany!')

        user.email_user(
            'Reset your password',
            f'Please click on the link for a password reset:'
            f' http://{self.request.get_host()}/user/reset/{token}')

        return super().form_valid(form)


class ResetPasswordValidateTokenChangePassword(FormView):
    template_name = 'user/reset_change_password.html'
    form_class = forms.PaswordResetSetPasswordForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        user = models.UserResetToken.objects.get(token=self.kwargs.get('token')).user
        user.set_password(form.cleaned_data['new_password'])
        user.save()

        messages.success(self.request, 'Hasło zostało zmienione!')
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        user_token = kwargs.get('token')

        save_token = models.UserResetToken.objects.filter(token=user_token).first()

        if not save_token:
            messages.error(request, 'Link do zmiany hasła jest nieprawidłowy!')
            return redirect(reverse_lazy('user:login'))

        if save_token.used:
            messages.error(request, 'Link do zmiany hasła został już wykorzystany!')
            return redirect(reverse_lazy('user:login'))

        save_token.used = True
        save_token.save()

        return super().get(request, *args, **kwargs)

backend/user/templates/user/change_password.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {% endblock %}

{% block content %}
    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
                <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
                <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>

            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a>
                </li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>
    </header>


    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">Zmień hasło!</input>
    </form>

{% endblock %}


{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/user/templates/user/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {% endblock %}

{% block content %}

    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
            </ul>

            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>
    </header>

    <section id="help" class="help">
        <h2>Szczegóły konta</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="{% url 'user:detail' 'donations_in_progress' %}" class="XD">Dary w trakcie
                przekazywania</a></li>
            <li data-id="2"><a href="{% url 'user:detail' 'realized_donations' %}" class="XD">Dary odebrane</a>
            </li>
            <li data-id="3"><a href="{% url 'user:detail' 'user_detail' %}" class="XD">Informacje o koncie</a>
            </li>
        </ul>

        <!-- SLIDE 1 -->

        <div class="help--slides active" data-id="1">
            <ul class="help--slides-items">


                {% if donations_in_progress %}
                    {% for donation in donations_in_progress %}
                        <li>
                            <div class="col">
                                <div class="title">Fundacja: {{ donation.institution.name }}</div>
                                <div class="subtitle">Cel i misja: {{ donation.institution.decription }}.</div>
                            </div>
                            <div class="col">
                                <div class="text">
                                    <a href="{% url 'user:taken' donation.pk %}">Potwierdź odebranie!</a></div>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}



                {% if realized_donations %}
                    {% for donation in realized_donations %}
                        <li>
                            <div class="col">
                                <div class="title">Fundacja "{{ donation.institution.name }}"</div>
                                <div class="subtitle">Cel i misja: {{ donation.institution.decription  }}.</div>
                            </div>
                            <div class="col">
                                <div class="text">Data odebrania: {{ donation.pick_up_date }}</div>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}


                {% if user_detail %}
                    <li>
                        <div class="col">
                            <div class="title">Twój e-mail:</div>
                        </div>
                        <div class="col">
                            <div class="text">{{ user_detail.email }}</div>
                        </div>
                    </li>
                    <li>
                        <div class="col">
                            <div class="title">Twoje imię:</div>
                        </div>
                        <div class="col">
                            <div class="text">{{ user_detail.username }}</div>
                        </div>
                    </li>
                    <li>
                        <div class="col">
                            <div class="title">Twoje nazwisko:</div>
                        </div>
                        <div class="col">
                            <div class="text">{{ user_detail.last_name }}</div>
                        </div>
                    </li>
                {% endif %}


            </ul>
        </div>
    </section>
    </body>

{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {% endblock %}

{% block content %}
    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
                <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
                <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>

            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>
    </header>

    <section class="login-page">
        <h2>Zaloguj się</h2>

        {% for message in messages %}
            <p class="text"> {{ message }} </p>
        {% endfor %}

        <form method="post" action="">
            {% csrf_token %}

            <div class="form-group">
                <label for="user_email"></label>
                <input type="email" id="user_email" name="user_email" placeholder="Email"/>
            </div>

            <div class="form-group">

                {% if form.errors.password %}
                    <p>{{ form.errors.password }}</p>
                {% endif %}

                <label for="password"></label>
                <input type="password" id="password" name="password" placeholder="Hasło"/>
                <a href="{% url 'user:reset_password' %}" class="btn btn--small btn--without-border reset-password">Przypomnij
                    hasło</a>
            </div>

            <div class="form-group form-group--buttons">
                <a href="{% url 'user:register' %}" class="btn btn--without-border">Załóż konto</a>
                <button class="btn" type="submit">Zaloguj się</button>
            </div>
        </form>
    </section>
    </body>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/user/templates/user/password_reset.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {% endblock %}

{% block content %}
    {#    <form action="" method="POST">#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {#        <button class="btn" type="submit">Wyślij</button>#}
    {#    </form>#}
    {##}


    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
                <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
                <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>
    </header>

    <section class="login-page">


        <form method="post" action="">
            {% csrf_token %}

            <h2>Wprowadź email:</h2>

            <div class="form-group">

                {% if form.errors.email %}
                    <p>{{ form.errors.email }}</p>
                {% endif %}

                <label for="email"></label>
                <input type="email" id="email" name="email" placeholder="Email"/>
            </div>

            <div class="form-group form-group--buttons">
                <button class="btn" type="submit">Zresetuj hasło!</button>
            </div>
        </form>
    </section>
    </body>

{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
                <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
                <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>

            <ul>
                <ul>
                    <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                    <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a>
                    </li>
                    <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                    <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                        organizacje</a></li>
                    <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
                </ul>
            </ul>
        </nav>
    </header>

    <section class="login-page">
        <h2>Załóż konto</h2>
        <form method="post" action="">
            {% csrf_token %}

            {% if form.errors %}
                <p>{{ form.errors }}</p>
            {% endif %}
            <div class="form-group">
                {% if form.errors.username %}
                    <p>{{ form.errors.username }}</p>
                {% endif %}
                <label for="username"></label>
                <input type="text" id="username" name="username" placeholder="Imię"/>
            </div>

            <div class="form-group">
                {% if form.errors.last_name %}
                    <p>{{ form.errors.last_name }}</p>
                {% endif %}
                <label for="last_name"></label>
                <input type="text" id="last_name" name="last_name" placeholder="Nazwisko"/>
            </div>

            <div class="form-group">
                {% if form.errors.emial %}
                    <p>{{ form.errors.emial }}</p>
                {% endif %}
                <label for="email"></label>
                <input type="email" id="email" name="email" placeholder="Email"/>
            </div>

            <div class="form-group">
                {% if form.errors.password %}
                    <p>{{ form.errors.password }}</p>
                {% endif %}
                <label for="password"></label>
                <input type="password" id="password" name="password" placeholder="Hasło"/>
            </div>

            <div class="form-group">
                <label for="re_password"></label>
                <input type="password" id="re_password" name="re_password" placeholder="Powtórz hasło"/>
            </div>

            <div class="form-group form-group--buttons">
                <a href="{% url 'user:login' %}" class="btn btn--without-border">Zaloguj się</a>
                <button class="btn" type="submit">Załóż konto</button>
            </div>
        </form>
    </section>
    </body>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}

backend/user/templates/user/reset_change_password.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {% endblock %}

{% block content %}
    {#    <form action="" method="POST">#}
    {#        {% csrf_token %}#}
    {#        {{ form.as_p }}#}
    {#        <button class="btn" type="submit">Wyślij</button>#}
    {#    </form>#}
    {##}


    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
                <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
                <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>
            <ul>
                <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
                <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                    organizacje</a></li>
                <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
                <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
        </nav>
    </header>

    <section class="login-page">


        <form method="POST" action="">

            {% csrf_token %}

            <h2>Wprowadź nowe hasło!:</h2>

            <div class="form-group">

                {% if form.errors.new_password %}
                    <p>{{ form.errors.new_password }}</p>
                {% endif %}

                <label for="new_password"></label>
                <input type="password" id="new_password" name="new_password" placeholder="Nowe hasło..."/>
            </div>

            <div class="form-group">

                {% if form.errors.re_new_password %}
                    <p>{{ form.errors.re_new_password }}</p>
                {% endif %}

                <label for="re_new_password"></label>
                <input type="password" id="re_new_password" name="re_new_password" placeholder="Powtórz hasło..."/>
            </div>


            <div class="form-group form-group--buttons">
                <button class="btn" type="submit">Zresetuj hasło!</button>
            </div>
        </form>
    </section>
    </body>

{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/app-min.js' %}" defer async></script>
    <script src="{% static 'scripts/contact-form-minn.js' %}" defer async></script>
{% endblock %}