user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login', views.LoginUserView.as_view(), name='login'),
    path('register', views.RegiserUserView.as_view(), name='register'),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class LoginUserView(TemplateView):
    template_name = 'user/login.html'


class RegiserUserView(TemplateView):
    template_name = 'user/register.html'

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {% endblock %}

{% block content %}
    <body>
        <header>
          <nav class="container container--70">
            <ul class="nav--actions">
              <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
              <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>

            <ul>
              <li><a href="{% url 'home:landing_page' %}">Start</a></li>
              <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
              <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
              <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
              <li><a href="{% url 'home:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
              <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
            </ul>
          </nav>
        </header>

        <section class="login-page">
            <h2>Zaloguj się</h2>
            <form>
                <div class="form-group">
                    <input type="email" name="email" placeholder="Email"/>
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="Hasło"/>
                    <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
                </div>

                <div class="form-group form-group--buttons">
                    <a href="#" class="btn btn--without-border">Załóż konto</a>
                    <button class="btn" type="submit">Zaloguj się</button>
                </div>
            </form>
        </section>
    </body>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
    <body>
    <header>
        <nav class="container container--70">
            <ul class="nav--actions">
                <li><a href="{% url 'user:login' %}">Zaloguj</a></li>
                <li class="highlighted"><a href="{% url 'user:register' %}">Załóż konto</a></li>
            </ul>

            <ul>
                <ul>
                    <li><a href="{% url 'home:landing_page' %}">Start</a></li>
                    <li><a href="{% url 'home:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a>
                    </li>
                    <li><a href="{% url 'home:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
                    <li><a href="{% url 'home:landing_page' %}#help" class="btn btn--without-border">Fundacje i
                        organizacje</a></li>
                    <li><a href="{% url 'home:landing_page' %}#contact" class="btn btn--without-border">Kontakt</a></li>
                </ul>
            </ul>
        </nav>
    </header>

    <section class="login-page">
        <h2>Załóż konto</h2>
        <form>
            <div class="form-group">
                <input type="text" name="name" placeholder="Imię"/>
            </div>
            <div class="form-group">
                <input type="text" name="surname" placeholder="Nazwisko"/>
            </div>
            <div class="form-group">
                <input type="email" name="email" placeholder="Email"/>ś
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="Hasło"/>
            </div>
            <div class="form-group">
                <input type="password" name="password2" placeholder="Powtórz hasło"/>
            </div>

            <div class="form-group form-group--buttons">
                <a href="login.html" class="btn btn--without-border">Zaloguj się</a>
                <button class="btn" type="submit">Załóż konto</button>
            </div>
        </form>
    </section>
    </body>
{% endblock %}